Weasyl/weasyl

- static/public.css
- templates/control/edit_emailpassword.html
- weasyl/controllers/settings.py
This is so we can tell people to check if their email address is up to date and if not they can date it.
> Display current email on control/editemailpassword

- weasyl/test/test_collection.py
This makes the tests pass, though that’s not saying much.
> Update collection tests to use pending_accept

- weasyl/character.py
- weasyl/comment.py
- weasyl/controllers/api.py
- weasyl/controllers/urls.py
- weasyl/favorite.py
- weasyl/journal.py
I tried to as closely replicate existing API methods. Let me know if there is anything that needs to be changed.
> Add API methods for journals and characters

- weasyl/collection.py
Collection thumbnails would always show the custom thumbnail. The issue
was that they didn't include the subtype in the select.
> Make collection thumbnails respect generated/custom preference

- .gitignore
Oops! I noticed this as soon as I started trying to change it.
> Don't ignore all of libweasyl

- Makefile
> Fix upgradedb in Makefile.

- static/public.css
- templates/common/page_end.html
- weasyl/define.py
It looks like this. 
The sha links to that revision on GitHub, the line of text just links to the GitHub page.
> Add link to GitHub in footer

- static/scripts.js
This adds a confirm before removing a friend, as mentioned in #9.
> Add confirm for removing a friend

- libweasyl/libweasyl/compat.py
- libweasyl/libweasyl/decorators.py
- libweasyl/libweasyl/models/content.py
- libweasyl/libweasyl/models/helpers.py
- libweasyl/libweasyl/test/test_text.py
- libweasyl/libweasyl/text.py
- libweasyl/setup.cfg
- setup.cfg
- weasyl/controllers/user.py
- weasyl/search.py
Makes it possible to `flake8 .` again for a thorough check.
Please merge #46 before this.
> Apply weasyl flake8 rules to libweasyl

- weasyl/controllers/general.py
My fault for wanting uppercase constants.
> Fix general's use of COUNT_LIMIT

- weasyl/image.py
- weasyl/journal.py
- weasyl/test/test_journal.py
- weasyl/welcome.py
> Remove unused functions

- config/site.config.txt.example
- libweasyl/libweasyl/alembic/alembic.ini.example
- libweasyl/libweasyl/conftest.py
- libweasyl/requirements.txt
- weasyl/define.py
Compatible with PyPy and might resolve an elusive SystemError. `site.config.txt`s and `alembic.ini`s will have to be updated.
> Use psycopg2cffi instead of psycopg2

- .travis.yml
- weasyl/blocktag.py
- weasyl/collection.py
- weasyl/controllers/api.py
- weasyl/controllers/interaction.py
- weasyl/define.py
- weasyl/errorcode.py
- weasyl/favorite.py
- weasyl/searchtag.py
- weasyl/test/conftest.py
- weasyl/test/db_utils.py
- weasyl/test/test_collection.py
- weasyl/test/test_submission.py
> Use PostgreSQL 9.5’s ON CONFLICT to avoid exceptions and logged errors

- weasyl/followuser.py
- weasyl/resetpassword.py
> Use ON CONFLICT for password resets and followuser

- weasyl/blocktag.py
- weasyl/controllers/api.py
- weasyl/searchtag.py
Comprises two equivalent but different implementations of the same tag prefix search in different modules and one controller with no associated route.
> Remove unused tag suggestion components

- templates/admincontrol/admincontrol.html
- templates/admincontrol/finduser.html
- templates/modcontrol/modcontrol.html
- weasyl/controllers/admin.py
- weasyl/controllers/moderation.py
- weasyl/controllers/urls.py
For #139.
Moves /modcontrol/finduser to /admincontrol/finduser.
> Move /modcontrol/finduser to /admincontrol/finduser

- weasyl/avatar.py
- weasyl/banner.py
- weasyl/character.py
- weasyl/image.py
- weasyl/media.py
- weasyl/submission.py
- weasyl/thumbnail.py
> Image cleanup

- weasyl/controllers/api.py
Introduced in d473003b9be13ce0687fc78c39321a1832d3413d.
> Remove leftover `self`s from controller helpers

- weasyl/oauth2.py
https://sentry.weasyldev.com/weasyl/weasyl/issues/1433/
@hyena, does this need to be inserted somewhere else?
> Fix iteritems call

- weasyl/oauth2.py
Essentially, this doesn’t work at all right now.
> Encode OAuth headers

- templates/admincontrol/manageuser.html
- weasyl/controllers/admin.py
- weasyl/controllers/settings.py
- weasyl/profile.py
- weasyl/test/test_profile.py
For #147, allows admins to remove social/contact links from users' profiles.
> Add UI for admins to remove user social links.

- weasyl/controllers/api.py
- weasyl/controllers/routes.py
- weasyl/errorcode.py
- weasyl/middleware.py
- weasyl/wsgi.py
Happens to resolve #156, #157, and #160.
> Use renderers for API views

- weasyl/image.py
I broke this while reverting the merge earlier.
> Reapply weasyl.image parts of 1d9c5ebb1a7a33cd1e47e8514bebedd18c5c0053

- templates/admincontrol/manageuser.html
- weasyl/controllers/admin.py
- weasyl/login.py
Now nothing is stored in `additional_data`. SFW mode probably should be, though.
Addresses #158.
> Remove “impersonate user” feature

- weasyl/controllers/settings.py
> Return to user management when editing stream settings as a moderator

- templates/submit/literary.html
It’s Google, so I figure this is enough despite the browser support.
> Add rel="noopener" to external target="_blank" link

- libweasyl/libweasyl/alembic/versions/cbe0ea91af79_remove_non_original_audio_upload_report_.py
- weasyl/macro.py
> Remove “Non-original audio upload” report type

- templates/directorcontrol/globaltagrestrictions.html
https://sentry.weasyldev.com/weasyl/weasyl/issues/1536/
> Fix global tag restriction display

- weasyl/submission.py
Integer division was not intended and breaks tests occasionally.
> Use float division for Recently Popular calculation

- weasyl/middleware.py
I'm not sure how this worked in the first place.
> Remove key parameter to cookie setting

- libweasyl/libweasyl/alembic/env.py
- libweasyl/libweasyl/models/tables.py
- libweasyl/requirements.txt
Only affects the length limit on `userinfo.gender`.
> Configure Alembic to detect column type and default changes

- libweasyl/libweasyl/defang.py
- libweasyl/libweasyl/test/test_text.py
- static/scripts.js
> Unwrap elements instead of removing them; allow `<del>`

- templates/control/edit_streaming.html
- weasyl/controllers/admin.py
- weasyl/controllers/content.py
- weasyl/controllers/director.py
- weasyl/controllers/general.py
- weasyl/controllers/info.py
- weasyl/controllers/moderation.py
- weasyl/controllers/settings.py
- weasyl/controllers/two_factor_auth.py
- weasyl/controllers/user.py
- weasyl/controllers/weasyl_collections.py
A page should have a title. ``Weasyl`` helps identify the site, but if I have 10 ``Weasyl`` tabs, what are they? This PR adds titles to rendered pages by adding in the ``title`` parameter, along with a title.
I _think_ I have gotten all of the pages, or at least the fruit easily seen on the proverbial tree.
> Add page titles for pages which lack them

- weasyl/controllers/info.py
- weasyl/controllers/routes.py
Overlooked in f3bec9dcdc706842711d7ae1efd00a760234bd55.
> Remove routes for guideline change pages

- libweasyl/libweasyl/alembic/versions/bf17041bf782_remove_moderate_rating_from_sfw_settings.py
Overlooked in the last migration.
> Remove moderate rating from SFW settings

- .travis.yml
> Use PostgreSQL 9.6 for CI

- weasyl/test/web/test_journals.py
- weasyl/test/web/wsgi.py
> Add some journal WebTests

- etc/requirements.txt
- weasyl/character.py
- weasyl/controllers/decorators.py
- weasyl/controllers/user.py
- weasyl/submission.py
- weasyl/test/web/test_characters.py
- weasyl/test/web/test_site_updates.py
Coverage for #259; depends on #268.
> Add some character WebTests

- weasyl/character.py
- weasyl/files.py
- weasyl/journal.py
- weasyl/thumbnail.py
Post-#254 and -#258 cleanup reducing the number of jobs each function and module does.
> Clean up weasyl.files

- Makefile
- Vagrantfile
Built a newer Debian .box file based on 9.3 for testing and possible inclusion in the project.
> Use a newer vagrant .box file

- weasyl/moderation.py
> Include original rating when editing ratings in bulk

- config/site.config.txt.example
- weasyl/commishinfo.py
https://www.ecb.europa.eu/stats/policy_and_exchange_rates/euro_reference_exchange_rates/html/index.en.html
> Use ECB exchange rates

- libweasyl/libweasyl/defang.py
- libweasyl/libweasyl/test/test_text.py
> Add missing rel="nofollow" for external scheme-relative URLs

- templates/control/edit_profile.html
Fixes https://sentry.weasyldev.com/weasyl/weasyl/issues/1762/.
> Align maxlength of “location” profile field with database column

- .gitignore
- libweasyl/libweasyl/models/users.py
- pyramid.md
- weasyl/controllers/decorators.py
- weasyl/define.py
- weasyl/login.py
- weasyl/middleware.py
- weasyl/sessions.py
- weasyl/test/conftest.py
- weasyl/test/web/test_blacklist.py
- weasyl/test/web/test_characters.py
- weasyl/test/web/test_journals.py
- weasyl/test/web/test_login.py
- weasyl/test/web/test_site_updates.py
- weasyl/test/web/wsgi.py
The first cleanup step for the session table.
See the commit summary of 5322eaca0ca86f94ba8ffe157aa0049a661e4d96.
> Stateless guest sessions

- weasyl/message.py
https://sentry.weasyldev.com/weasyl/weasyl/issues/1770/
> Fix notifications about characters with no tags

- libweasyl/libweasyl/alembic/versions/664a23bbc217_add_permitted_senders_table.py
- libweasyl/libweasyl/models/tables.py
- weasyl/note.py
- weasyl/test/web/test_notes.py
https://twitter.com/buckdasystem/status/1023250072337874947
> Allow replies by default even when notes are restricted

- config/weasyl-staff.example.py
- libweasyl/libweasyl/alembic/versions/7f0e262d6370_add_post_as_wesley_option_to_site_.py
- libweasyl/libweasyl/models/site.py
- libweasyl/libweasyl/models/tables.py
- libweasyl/libweasyl/staff.py
- templates/admincontrol/siteupdate.html
- templates/etc/site_update.html
- templates/etc/site_update_list.html
- weasyl/controllers/admin.py
- weasyl/siteupdate.py
- weasyl/staff_config.py
Implements #414.
@ikanimew This needs to be deployed with a new setting at the end of `config/weasyl-staff.py`: `wesley = 2000`.
> Add option to post site updates as Wesley

- weasyl/comment.py
> Fix comments on journals and characters

- weasyl/controllers/interaction.py
- weasyl/ignoreuser.py
Performs the action, but causes an error page to be displayed.
> Fix race when ignoring a user using the profile page button

- .gitignore
- .travis-install.sh
- Makefile
- etc/requirements.txt
- libweasyl/.gitignore
- setup.py
This has been on the list for a while.
> Upgrade Twisted

- static/scripts.js
> Allow scripts to continue working when storage is disabled

- libweasyl/libweasyl/alembic/versions/a48c39473126_add_favorite_count_to_submissions.py
- libweasyl/libweasyl/models/tables.py
- weasyl/define.py
- weasyl/favorite.py
- weasyl/submission.py
- weasyl/welcome.py
and new favorites. This will eventually be able to save a query when viewing submissions and make the Recently Popular query much faster.
> Maintain favorite count in a column for new submissions

- weasyl/welcome.py
instead of completely ignoring them. They could be important.
> Log exceptions when inserting notifications

- config/site.config.txt.example
- libweasyl/libweasyl/alembic/versions/8e98a1be126e_add_index_on_submission_popularity_score.py
- libweasyl/libweasyl/models/tables.py
- weasyl/submission.py
- weasyl/test/db_utils.py
- weasyl/test/test_favorite.py
- weasyl/test/test_submission.py
> Use favorite count column to create recently popular list and display… favorite count

- weasyl/comment.py
- weasyl/define.py
Any other uses of the affected functions are probably bugs.
> Be more restrictive about the exceptions we ignore

- assets/scss/site.scss
- templates/common/user_tools.html
by reserving space with an inline SVG.
> Avoid distracting layout change as banner loads

- weasyl/spam_filtering.py
For example, a temporary name resolution failure; it doesn't make sense to force-drop the entire submitted content if Akismet goes down, so behave as if the submission were ham.
We've had a mess of these beginning today, going by Sentry. Since ``Oct 31, 2019 5:38:28 PM UTC``, 119 events affecting 41 users.
Fixes Sentry ID WEASYL-164.
> Don't raise an error if the Akismet backend connection fails.

- weasyl/controllers/user.py
- weasyl/define.py
- weasyl/macro.py
- weasyl/templates/common/page_end.html
- weasyl/templates/email/email_in_use_account_creation.html
- weasyl/templates/error/error.html
- weasyl/templates/help/collections.html
- weasyl/templates/help/community.html
- weasyl/templates/help/faq.html
- weasyl/templates/help/thanks.html
We’ll at least be able to reply that support isn’t forthcoming this way.
> Make support address configurable and set it to one that’s checked

- libweasyl/libweasyl/alembic/versions/7a317ce25845_add_login_voucher.py
- libweasyl/libweasyl/models/tables.py
- libweasyl/setup.py
- weasyl/commishinfo.py
- weasyl/controllers/content.py
- weasyl/controllers/info.py
- weasyl/controllers/interaction.py
- weasyl/controllers/profile.py
- weasyl/controllers/routes.py
- weasyl/controllers/settings.py
- weasyl/controllers/user.py
- weasyl/controllers/weasyl_collections.py
- weasyl/define.py
- weasyl/errorcode.py
- weasyl/login.py
- weasyl/moderation.py
- weasyl/note.py
- weasyl/profile.py
- weasyl/resetpassword.py
- weasyl/shout.py
- weasyl/templates/common/comment_form.html
- weasyl/templates/common/comment_thread.html
- weasyl/templates/control/control.html
- weasyl/templates/error/unverified.html
- weasyl/templates/help/verification.html
- weasyl/test/db_utils.py
It’s a bit simplistic, but I hope it’s good enough to let us reopen registration.
> Invite mode

- libweasyl/libweasyl/alembic/versions/a1dac55f8355_add_optimized_image_media_selection_.py
- libweasyl/libweasyl/models/tables.py
- weasyl/media.py
- weasyl/submission.py
- weasyl/templates/detail/submission.html
See https://github.com/Weasyl/mediacopy.
> Add optimized image media selection

- weasyl/controllers/profile.py
- weasyl/favorite.py
The user is always present when these functions are called.
> Don’t treat user as optional when listing favorites

- weasyl/templates/detail/character.html
- weasyl/templates/detail/submission.html
Lets it work for characters and CDN2; simplifies Nginx configuration; makes behaviour consistent between development and production.
> Use `<a download>` for download button

- .travis.yml
- Vagrantfile
> Use Node 13

- weasyl/controllers/moderation.py
- weasyl/controllers/routes.py
Missing since before accessible history (2012-11-19). Found by @sl1-1.
> Remove with /modcontrol/edituserconfig route with missing implementation

- weasyl/moderation.py
- weasyl/templates/admincontrol/finduser.html
> Fix /admincontrol/finduser for removed login.settings

- libweasyl/libweasyl/alembic/versions/4b6fd0d48a2b_add_username_history.py
- libweasyl/libweasyl/models/tables.py
- weasyl/controllers/moderation.py
- weasyl/controllers/profile.py
- weasyl/controllers/routes.py
- weasyl/controllers/settings.py
- weasyl/define.py
- weasyl/embed.py
- weasyl/errorcode.py
- weasyl/login.py
- weasyl/moderation.py
- weasyl/profile.py
- weasyl/templates/control/control.html
- weasyl/templates/control/edit_profile.html
- weasyl/templates/control/username.html
- weasyl/templates/help/faq.html
- weasyl/test/login/test_create.py
- weasyl/test/web/test_login.py
- weasyl/useralias.py
> Allow users to change their own usernames

- weasyl/cache.py
- weasyl/middleware.py
- weasyl/weasyl.tac
- weasyl/wsgi.py
But also improve `?sql_debug` into `?query_debug`, which includes memcached and queries made in more tweens.
> Restore memcached stats headers

- weasyl/controllers/admin.py
- weasyl/controllers/content.py
- weasyl/controllers/decorators.py
- weasyl/controllers/interaction.py
- weasyl/controllers/profile.py
- weasyl/controllers/settings.py
- weasyl/controllers/two_factor_auth.py
- weasyl/controllers/user.py
- weasyl/error.py
- weasyl/errorcode.py
- weasyl/test/web/test_journals.py
- weasyl/test/web/test_site_updates.py
- weasyl/test/web/test_submissions.py
replace most uses of define.errorpage with raising WeasylError
> Error handling cleanup

- weasyl/folder.py
- weasyl/templates/user/profile.html
and serve a WebP thumbnail when available.
> Obey custom thumbnail display preference for folder previews

- weasyl/folder.py
The error messages around this are pretty confusing.
> Allow folder to become subfolder even when it has hidden children

- weasyl/templates/user/journals.html
- weasyl/test/web/test_journals.py
> Fix journal lists of profiles with Unicode usernames

- weasyl/controllers/interaction.py
- weasyl/controllers/profile.py
- weasyl/controllers/user.py
- weasyl/templates/email/verified.html
- weasyl/templates/help/verification.html
- weasyl/templates/user/profile.html
- Send e-mail notification when users are verified
- Give verification advice more convenient to staff verifying
- Fix missing anchors on verification help page
- Allow following without verification
- Allow moderators to view unverified profiles
> Improve verification

- Dockerfile
- README-docker.md
Allowing Python changes without a rebuild makes development on Docker less painful.
> Docker improvements

- etc/requirements.txt
- libweasyl/libweasyl/ratings.py
- libweasyl/setup.py
- weasyl/profile.py
- weasyl/search.py
We don’t do translations. If we ever start, we won’t miss that rating text was once set up for it.
Also includes removal of unused code.
> Remove translationstring

- weasyl/controllers/general.py
- weasyl/search.py
Replaces #797 has requested changes by charmander
> Remove dependency on storify from controllers/general.py

- weasyl/controllers/profile.py
> remove dependency on storify from controllers/profile.py

- weasyl/controllers/detail.py
- weasyl/controllers/general.py
- weasyl/controllers/settings.py
- weasyl/controllers/weasyl_collections.py
- weasyl/templates/admincontrol/acctverifylink.html
- weasyl/templates/common/page_end.html
- weasyl/templates/error/error.html
- weasyl/templates/etc/signup.html
- weasyl/templates/submit/character.html
- weasyl/templates/submit/journal.html
- weasyl/templates/submit/literary.html
- weasyl/templates/submit/multimedia.html
- weasyl/templates/submit/reupload_cover.html
- weasyl/templates/submit/visual.html
Most links were this way already, as they should be, but making sure all of them are is cleaner and avoids a duplicate search result.
> Make “/” the canonical home page path

- libweasyl/libweasyl/images.py
- weasyl/character.py
- weasyl/image.py
- weasyl/media.py
- weasyl/submission.py
Plus minor documentation corrections and removal of unused parts.
Python 3 changes based on this.
> Combine functions duplicated between weasyl.image and libweasyl.images

- libweasyl/libweasyl/text.py
Part of coverage improvements!
> Remove unused Markdown image limit

- .github/dependabot.yml
- Dockerfile
- etc/requirements.txt
- libweasyl/setup.py
- weasyl/test/test_followuser.py
- weasyl/test/test_search.py
> Post-Python-3 package changes

- etc/requirements.txt
- weasyl/templates/manage/avatar.html
- weasyl/test/web/test_avatar.py
Fixes WEASYL-1DX and WEASYL-1E3.
> Fix animated GIF processing

- weasyl/submission.py
- weasyl/test/db_utils.py
- weasyl/test/web/test_submissions.py
> Fix rating restriction on folder navigation between own submissions in SFW mode

- assets/js/scripts.js
- assets/scss/site.scss
- weasyl/templates/manage/avatar.html
- weasyl/templates/manage/banner.html
- weasyl/templates/submit/character.html
- weasyl/templates/submit/literary.html
- weasyl/templates/submit/multimedia.html
- weasyl/templates/submit/reupload_cover.html
- weasyl/templates/submit/reupload_submission.html
- weasyl/templates/submit/visual.html
They have problems:
- appearing empty when form state is restored, e.g. by returning to the page with browser back/forward
- no focus state
- a strange hover/click area
- inaccurate form validation message positioning
and the default browser appearance isn’t bad enough to justify the complexity of the current implementation.
> Remove styled file inputs

- config/site.config.txt.example
- etc/requirements.txt
- weasyl/cache.py
- weasyl/commishinfo.py
- weasyl/define.py
- weasyl/image.py
- weasyl/middleware.py
- weasyl/test/conftest.py
- weasyl/wsgi.py
The API isn’t great and there’s already a workaround for a bug/glaring omission, but the library is actively maintained and the new performance/tracing features are nice.
> Upgrade Sentry client from raven to sentry-sdk

- libweasyl/libweasyl/test/test_text.py
- libweasyl/libweasyl/text.py
> Fix autolinking applied incorrectly inside in HTML links

- docker-compose.yml
- libweasyl/libweasyl/models/helpers.py
- libweasyl/libweasyl/models/tables.py
- weasyl/frienduser.py
- weasyl/searchtag.py
and make some builder queries cacheable.
> Address SQLAlchemy 1.4 warnings

- libweasyl/libweasyl/alembic/versions/41a6dbe0266d_index_submission_userid_submitid.py
- libweasyl/libweasyl/models/tables.py
- weasyl/controllers/profile.py
- weasyl/pagination.py
- weasyl/submission.py
- weasyl/templates/common/page_navigation.html
for users with large numbers of submissions. ~300 ms reduced to ~10 ms for ~5,000 submissions, for example.
> Improve performance of submission, gallery pages

- libweasyl/libweasyl/alembic/versions/1fbcfecd195e_create_journal_and_character_hidden_.py
- libweasyl/libweasyl/models/content.py
- libweasyl/libweasyl/models/tables.py
- weasyl/character.py
- weasyl/controllers/content.py
- weasyl/controllers/moderation.py
- weasyl/controllers/routes.py
- weasyl/journal.py
- weasyl/macro.py
- weasyl/moderation.py
by initializing the columns to `NULL` for existing content/content created before the deployment of this app version, then filling them in and keeping them synchronized for future new, edited, and removed content.
> Prepare to split journal and character hidden/friends-only into columns

- weasyl/controllers/settings.py
- weasyl/controllers/user.py
- weasyl/errorcode.py
- weasyl/login.py
- weasyl/profile.py
- weasyl/resetpassword.py
- weasyl/templates/control/edit_emailpassword.html
- weasyl/templates/etc/resetpassword.html
- weasyl/templates/etc/signup.html
- weasyl/test/login/test_create.py
- weasyl/test/login/test_get_account_verification_token.py
- weasyl/test/resetpassword/test_reset.py
- weasyl/test/test_profile.py
1. **remove repeat/redundant inputs** (you are here)
2. replace date of birth entry with checkboxes
3. log in automatically after confirming e-mail address
4. handle repeated registration attempts/failure to receive verification e-mail better
> Streamline signup (part 1)

- libweasyl/libweasyl/alembic/versions/1512aa4220d3_add_session_last_active.py
- libweasyl/libweasyl/models/tables.py
- weasyl/middleware.py
Preparation for expiring old sessions.
> Keep track of session last active timestamp

- .github/workflows/codeql-analysis.yml
- .lgtm.yml
> Add CodeQL analysis

- .github/workflows/codeql-analysis.yml
The documentation on this is a little sparse.
> ci: Enable more CodeQL queries?

- weasyl/controllers/director.py
I refuse to write a regression test for this
> Fix removal of blocked account e-mail domains for Python 3

- assets/scss/site.scss
- design/padlock.html
- weasyl/controllers/settings.py
- weasyl/define.py
- weasyl/profile.py
- weasyl/templates/common/page_start.html
- weasyl/templates/control/edit_preferences.html
- weasyl/templates/help/faq.html
- Indicate when SFW mode does nothing and link to the page to configure it
- Remove option to set rating other than General for SFW mode
This should make the UI much clearer and easier to understand, at the expense of some niche configurability.
Fixes #470.
> SFW mode improvements

- containers/prometheus/Dockerfile
- containers/prometheus/prometheus.yml
- docker-compose.yml
- gunicorn.conf.py
- poetry.lock
- pyproject.toml
- weasyl/index.py
- weasyl/metrics.py
- weasyl/middleware.py
- weasyl/wsgi.py
The Prometheus client library for Python seems not great, but we really need metrics to get a sense of some upcoming performance improvements.
> Expose some initial Prometheus metrics

- weasyl/test/conftest.py
Halves the time to run `weasyl.test`.
> Configure Pyramid registry only once across a test session, instead of once for each test

- poetry.lock
- pyproject.toml
Might also fix some sporadic issues with stuck workers and temporary file leaks?
> Upgrade Gunicorn to version 23.0.0

- weasyl/collection.py
- weasyl/templates/detail/submission.html
- weasyl/test/test_collection.py
> Collections security fixes and improvements

- README.md
- weasyl/templates/edit/character.html
- weasyl/templates/edit/journal.html
- weasyl/templates/edit/submission.html
- weasyl/templates/help/faq.html
- weasyl/templates/submit/character.html
- weasyl/templates/submit/journal.html
- weasyl/templates/submit/literary.html
- weasyl/templates/submit/multimedia.html
- weasyl/templates/submit/visual.html
This started as an update to the file size limits in the FAQ, but I'm taking the opportunity to look over the user-facing and developer-facing documentation and seeing what I can add or update.
> Various documentation updates

- weasyl/middleware.py
> Redact more secrets when logging requests

- assets/js/message-list.js
- assets/js/scripts.js
- assets/scss/_theme.scss
- assets/scss/components/_page-navigation.scss
- assets/scss/components/_private-messages.scss
- assets/scss/site.scss
- build.js
- libweasyl/models/tables.py
- weasyl/controllers/interaction.py
- weasyl/define.py
- weasyl/errorcode.py
- weasyl/note.py
- weasyl/templates/common/page_navigation.html
- weasyl/templates/note/compose.html
- weasyl/templates/note/message_list.html
The first commit, a security fix, is already deployed.
> Private message list improvements

- weasyl/moderation.py
Fixes #416 
~~Double-backslash prevents the error case you brought up in the issue.~~
> Fix error when searching for users with symbols (#416)

- libweasyl/oauth.py
- weasyl/oauth2.py
- weasyl/templates/oauth2/authorize.html
Still not to be reenabled just yet.
> Restore OAuth to previous working condition

- docker-compose.yml
> docker-compose: Quote environment strings in Docker Compose config

- weasyl/profile.py
- weasyl/templates/control/edit_profile.html
Oldest recorded human was 122 years 164 days but we're pretty sure she wasn't a Weasyl user. Either way, it might happen and we shouldn't be ageist.
(no, this comment isn't entirely serious but we might as well fix this)
related to #1447
> profile.py: allow ages over 100

- weasyl/controllers/profile.py
> Count friends-only posts on own profile

- weasyl/controllers/info.py
> Skip username fetch for verification help page as guest

- assets/scss/components/_edit-profile.scss
- assets/scss/site.scss
No functional changes, but it'll make future progress on #1477 easier once I figure out a design, and it improves maintainability by cutting down the size of the large `site.scss` file.
> Move profile editor SCSS into its own file

- weasyl/search.py
- weasyl/test/test_search.py
> Exclude pending friends from within-friends search (#1482)

- weasyl/templates/control/edit_tagrestrictions.html
> Apply Weasyl theme to Community Tagging Restrictions textbox

- weasyl/templates/common/page_start.html
> Remove leftover reference to Weasyl Twitter account

- weasyl/controllers/detail.py
Match what submissions do, as closely as possible.
This quick PR brought to you by the free Wi-Fi on a coach bus I'm currently on.
Closes #1512
> Add embeds for characters and journals

- libweasyl/configuration.py
- libweasyl/conftest.py
- libweasyl/models/media.py
- libweasyl/staff.py
- weasyl/staff_config.py
- weasyl/test/conftest.py
- weasyl/test/test_staff_config.py
- weasyl/wsgi.py
Separated out from some other cleanup for easier merging.
> Improve typing of libweasyl global state

- assets/js/submit.js
- build.ts
- weasyl/templates/submit/literary.html
- weasyl/templates/submit/multimedia.html
- weasyl/templates/submit/visual.html
> Add client-side validation for submission tags

- assets/js/dom.js
- assets/js/login-box.js
- assets/js/scripts.js
- assets/js/util/has-modifier-keys.js
- assets/scss/_reset.scss
- assets/scss/_theme.scss
- assets/scss/components/_login.scss
- assets/scss/site.scss
- build.ts
- weasyl/controllers/two_factor_auth.py
- weasyl/controllers/user.py
- weasyl/define.py
- weasyl/login.py
- weasyl/oauth2.py
- weasyl/templates/common/page_start.html
- weasyl/templates/etc/login_box.html
- weasyl/templates/etc/signin.html
- weasyl/test/login/test_authenticate_bcrypt.py
> Login form/box improvements
