- weasyl/files.py
- weasyl/login.py
Functions in `weasyl.files` and use of the `loginaddress` table, which is empty in production.
> Remove some unused parts

- etc/requirements.txt
Updates Weasyl Python library dependencies to current. Depends on libweasyl/#4 and its merge to master being tagged with 0.11.2.
> Update library requirements in requirements.txt

- templates/common/page_end.html
Changes the year in the copyright line to the current year; previously, the line had 2015 as the end-year.
> Page footer (page_end.html): Update copyright date

- static/public.css
This looks like it was a side-effect of mordernizr being removed and
.csstransform rules no longer being applied.
There's still one more .csstranform rule in the CSS file that I'm
not really sure what to do about.
> Recenter the position of thumbs

- weasyl/character.py
- weasyl/comment.py
- weasyl/journal.py
There were a number of issues with #22 that this should resolve.
> Resolve a number of issues introduced with #22

- static/public.css
reported: https://forums.weasyl.com/vbulletin/showthread.php?8667-KitKat-browser-thumbnail-bug
https://twitter.com/DrKraest/status/739478234371379200
KitKat default browser and iOS <9.2 requires -webkit- prefix to css transform causing problems not remedied by #30
> Add webkit transform prefix for ios and android browsers

- README.rst
When virtualizing under a Windows host, Intel VT-x/EPT or AMD-V/RVI must be passed through to the guest OS, or Virtualbox will fail to properly bring up the Weasyl VM during the ``vagrant up`` command. No descriptive error is given by Vagrant in this instance, potentially leading to confusion.
> Add virtualization extension requirement to help section

- config/site.config.txt.example
- templates/etc/signup.html
- weasyl/controllers/user.py
- weasyl/define.py
Code updates to use the newer version of reCAPTCHA. Tests locally with production reCAPTCHA v2 keys work as expected, both with JavaScript and without scripting enabled. (The failure point during tests run on the Weasyl development VM in this situation is the inability to mail anything out. But that is well after any failure mode for the reCAPTCHA code.)
> Update reCAPTCHA version

- README.rst
Fixed a few instances of "Weasyl" not being capitalized outside of places where one would expect lowercase usage (such as path names); fixed a few instances of commands not being properly enclosed in double backticks.
> Capitalization and style fixes

- libweasyl/libweasyl/alembic/versions/9afc9a45510c_add_submission_tags_for_fast_searching.py
- libweasyl/libweasyl/models/tables.py
- libweasyl/libweasyl/ratings.py
- weasyl/controllers/general.py
- weasyl/search.py
- weasyl/searchtag.py
- weasyl/test/db_utils.py
- weasyl/test/test_search.py
This might make searches take less than 20 seconds. If it does, we should be able to use it for tag blacklists, too.
> Use array-based tag table to improve search performance

- CODE_OF_CONDUCT.md
- README.rst
The code of conduct is adapted from http://contributor-covenant.org/.
It has been altered slightly to account for the often explicit
content hosted by this project.
> Add a CODE_OF_CONDUCT.md

- templates/etc/search.html
- weasyl/controllers/general.py
- weasyl/search.py
- weasyl/test/test_search.py
- Use an array-based blocktag check (dropped query time from 18s to 3s in one case)
- Stop counting search results after 10,000 (maybe we can stop measuring query time in seconds)
> Improve search performance a bit more

- Makefile
Installs both the python libraries pytest and flake8 when 'make test' is run and neither of these libraries are installed in weasyl-env.
> Make 'make-test' work when pytest or flake8 not installed

- etc/requirements.txt
Fixes a bug at submit time to sentry in certain circumstances, where exceptions cause 'ValueError: too many values to unpack'.
> Update raven library version to 5.21.0

- weasyl/http.py
- weasyl/middleware.py
- weasyl/oauth2.py
- weasyl/test/test_http.py
- Restores friendly error pages by fixing #78
- Strips session ids from events
- Uses built-in fields for event data when available so Sentry can add useful widgets
Tested using a local Sentry instance.
> Sentry error-reporting improvements

- templates/detail/character.html
- templates/detail/journal.html
- templates/user/profile.html
- templates/user/shouts.html
Finish removing cached parameters from templates; leaving the 'cached=true' in broke the template when attempting to view the template in question.
No further instances of ``cached = true`` exist in templates per ``git grep cached``.
> Remove 'cached=true' from templates

- assets/scss/site.scss
Resolves Issue #72. Removes two SCSS rules that applied to the /thanks page's donator-list class. The rules removed were the same ones identified in the issue.
> Unbreak the Awesome People page (SCSS/CSS Styles)

- libweasyl/libweasyl/alembic/versions/d0bffaa55b06_index_favorites_by_unixtime.py
- libweasyl/libweasyl/models/tables.py
- weasyl/blocktag.py
- weasyl/index.py
- weasyl/searchtag.py
- weasyl/submission.py
- weasyl/test/test_submission.py
Taking advantage of the fact that you can’t favorite something before it’s created, this reduces the number of favorite rows read from 5.5 million to a few thousand. (It’s possible to do the same thing without adding an index, but this makes the query neater.)
> Speed up Recently Popular calculation

- weasyl/message.py
Currently, all journal notifications are visible, regardless of the user’s rating preferences – most noticeable when browsing using SFW mode. This fixes the behaviour to match submission notifications’.
> Filter journal notifications by rating

- libweasyl/libweasyl/alembic/versions/c8c088918278_index_media_by_sha256.py
- libweasyl/libweasyl/models/tables.py
Stops `MediaItem.fetch_or_create()` from scanning the entirety of the media table, a process that currently slows every upload down by about a second.
> Index media by sha256

- .editorconfig
- setup.cfg
Maybe the combination will help prevent all this trailing whitespace.
> Exclude weasyl-apidocs from flake8; add .editorconfig

- libweasyl/requirements.txt
Fixes <https://sentry.weasyldev.com/weasyl/weasyl/issues/1391/>; see <https://github.com/idan/oauthlib/pull/425>.
> Update oauthlib to 1.1.2

- weasyl/message.py
The API says tags should already be returned for the ``/api/messages/submissions`` endpoint; so return them. Proposed fix for #86.
Example output, using three submissions, one character. https://paste.weasyldev.com/show/Bl4xWt1qQ9egqlFJkPYO/
> Return tags with /api/messages/submissions call

- weasyl/controllers/api.py
It makes no sense and bypasses `login_required`, causing [errors][1].
[1]: https://sentry.weasyldev.com/weasyl/weasyl/issues/1416/
> Avoid checking tokens in api_method decorator

- README.rst
- STYLE_GUIDE.md
For #104 (replaces PR #106).
Integrates the Style and Best Practices Guide from the Wiki into the codebase as STYLE_GUIDE.md, linking to it via README.rst.
> Integrate style and best practices guide

- weasyl/controllers/weasyl_collections.py
These popped up in Sentry, but only once, because nobody uses collections.
> Miscellaneous bugfixes

- weasyl/controllers/general.py
This fixes category/subcategory/… being displayed when searching with `#user` and prevents an error from being thrown when `#character` or `#journal` results span multiple pages.
https://sentry.weasyldev.com/weasyl/weasyl/issues/1428/
> Pass correct search type to template when #-specified

- etc/requirements.txt
- libweasyl/requirements.txt
We haven't done this very recently and it's likely due. Also probably good to rule out any underlying library memory issues given what we're troubleshooting on the front end.
> Update library requirements in requirements files to newest non-betas

- weasyl/character.py
- weasyl/journal.py
Fixes #146. Additionally resolves the same issue with character-type items.
Fixes the incorrect logic of determining if the 'anyway' URL parameter is set to the string 'true'; previous code was looking for the string 'anyway' (when the URL was passing in "true").
> Restore moderator ability to view hidden characters and journals

- templates/note/message_view.html
- weasyl/controllers/moderation.py
- weasyl/controllers/routes.py
For #134.
Adds a button to the note page of a received note, which permits moderators to directly copy the contents of the note to the Staff Notes of the user who sent the note.
I opted to put the controller and code in the ``moderation`` section since it is only for moderators, however if there is a desire for it, I can shift it under the ``interaction`` controller and ``note.py``; as it is currently written, though, no additional imports are needed.
> Add ability to copy received note to staff notes

- libweasyl/libweasyl/html.py
- libweasyl/libweasyl/test/test_html.py
Not a live vulnerability:
* anyjson already does this escaping (not the `<!--`)
* we don’t use `inline_json` on any user input
but it’s still fragile, stupid and my fault.
> Escape </script> in inline JSON regardless of casing

- templates/submit/character.html
- templates/submit/journal.html
- templates/submit/literary.html
- templates/submit/multimedia.html
- templates/submit/visual.html
For #173.
Adds the HTML5 'required' attribute when possible to catch some input validation errors client-side, which would otherwise be caught server-side.
Does not address the search tag issue, unfortunately. I inspected the source of the tag, and however the JavaScript that's operating on the space/comma action adds a new ``<ul>`` item (or something along those lines), and as such it doesn't modify either the ``textarea`` or the ``input`` tags (though even the ``input`` tag isn't actually in the source templates; added by JS, maybe?). Here's the example on the live site of this behavior: https://i.sli.mg/hj3Ar7.png
> Add 'required' attribute where possible in submission pages

- libweasyl/libweasyl/models/users.py
- libweasyl/requirements.txt
Text fields are returned from the database as strings, but bcrypt expects bytes.
> Restore Python 3 compatibility in libweasyl password authentication

- templates/directorcontrol/emailblacklist.html
- weasyl/controllers/director.py
- Fixes alignment of text in the columns to be centered to match the centered column headings.
- Eschews the ``d.meta.tables`` method of adding a row, opting for raw SQL to leverage ``ON CONFLICT (domain_name) DO NOTHING`` to prevent errors in the event that a domain name is attempted to be added twice.
- Enforces the 252 character limit on the Python back-end (it was only relying on HTML length limits before).
- ~~Forces domain name to lowercase (because capitalization doesn't really matter)~~ This was already done in the ``d.meta.tables`` method of adding SQL, and was carried over in these changes.
> Miscellaneous fixes for the Login Email Blacklist

- libweasyl/libweasyl/alembic/versions/83e6b2a46191_track_most_recent_submission_time.py
- libweasyl/libweasyl/models/tables.py
- weasyl/submission.py
- weasyl/test/db_utils.py
Done in preparation of #192, this establishes a column on `profile` called `last_active` that stores the unixtime of when the user most recently created a submission, character or journal. This is done to improve performance of the Marketplace search query.
> Add last_active column to profile

- libweasyl/libweasyl/alembic/versions/eff79a07a88d_use_timestamp_column_for_latest_.py
- libweasyl/libweasyl/models/tables.py
`WeasylTimestampColumn` is for compatibility with very old code; it shouldn’t be used with new columns.
> Use TIMESTAMP column for latest submission time

- weasyl/commishinfo.py
Having the currency conversion ratio effectively inverted causes unexpected results in marketplace searches.
> Convert currencies correctly for min/max price filtering

- templates/etc/marketplace.html
- weasyl/commishinfo.py
addresses #203 
convert a user's display name to its canonical format before using it in links.
> Use LOGIN for building links to users

- libweasyl/libweasyl/text.py
- weasyl/files.py
“Missing submission/journal file” shouldn’t be ignored, and the Markdown renderer shouldn’t be the one to handle it.
> Remove unused `files.read` parameters; let errors propagate

- weasyl/controllers/detail.py
> Include `anyway` querystring parameter in canonical submission path

- weasyl/profile.py
- weasyl/submission.py
Addresses #221.
Obtains the current session via ``d.get_weasyl_session()``, then deletes all records from the ``session`` table where records match the ``userid`` for whom we just updated their password, and where the ``sessionid`` in the candidate record does not equal the ``sessionid`` in the session object.
> Invalidate all other sessions when a user's password is changed.

- weasyl/test/conftest.py
Because Fixer.io doesn't always return fast enough for tests to work, or otherwise fails. And because this also allows these tests to work in a non-online state. And because the tests should be deterministic, anyway.
I just took the output from ``http://api.fixer.io/latest?base=USD``, stuck it in a string, ran it through ``json.loads()``, and monkeypatch'ed the ``_fetch_rates`` function.
> Make the Marketplace tests deterministic in nature

- weasyl/middleware.py
Without this, the code will break in webob 1.10
> Remove a deprecated parameter from setting a cookie

- weasyl/two_factor_auth.py
Per discussion in Gitter, discussing the performance factor and how the recovery codes aren't exactly able to be brute-forced (easily, at least); the alternative was sha-256/512 unsalted, however per Charmander this 'makes it impossible to use a timing-unsafe lookup or comparison, as a side benefit'; lowers the bcrypt work-factor from 10 to the pyca/bcrypt minimum of 4.
No alterations needed to any other 2FA code. Bcrypt will handle Bcrypt.
> 2FA: Lower bcrypt work-factor to minimum

- libweasyl/libweasyl/alembic/versions/e50f34d62fd2_remove_incorrect_autoincrements.py
Several database copies exist in various states of mismatch with the migrations.
> Drop sequences only if they don’t exist

- templates/message/notifications.html
- weasyl/message.py
Addresses #212.
Linking to /shouts#cid only works if the link is visited while logged in, as the target user to whom the shout was sent. Adding the user to whom the shout was sent permits a more permanent link, and works if the link is copied and visited while logged or or sent to a different user if copied.
Effectively, this change makes this (in the ``/messages/notifications#comments`` section):
```
<a href="/~ikani" class="username">Ikani</a> left a <a href="/shouts#cid2610533">comment</a> on your shout page.
```
Into this:
```
<a href="/~ikani" class="username">Ikani</a> left a <a href="/shouts/kyra#cid2610533">comment</a> on your shout page.
```
> Shout notifications should link to /shouts/username#cid

- .travis.yml
- Makefile
- package-lock.json
- package.json
CI is currently failing because nvm is installing the latest version of Node while the node-sass dependency’s major version remains fixed.
> Install specific Node version in CI

- libweasyl/libweasyl/alembic/versions/088e13f2ae70_add_journal_content_column.py
- libweasyl/libweasyl/models/tables.py
- weasyl/journal.py
The first step in moving journal content out of files. Must be deployed first to avoid any period where new content could be discarded or where errors could be produced.
Also fixes the bug of journal entries being inserted before their files exist.
> Write new journal entries to database

- libweasyl/libweasyl/alembic/versions/f30dc3b5856a_move_journal_content_to_database.py
Should improve performance significantly, though I’m still not sure whether it’ll be enough given testing’s setup. (The original ran in under a minute with all files present locally.)
> Set journal content in one query

- weasyl/commishinfo.py
> Avoid error on non-ASCII search terms in Marketplace

- templates/user/journals.html
Introduced in 52b6bdcd9aaadbb74d6f35a5e67a1c2db6fb9c80. Linting for unused CSS rules might help catch this type of problem.
> Fix journal list container id

- weasyl/macro.py
A redirect is served if the target blog doesn’t support it.
> Default to HTTPS for Tumblr links

- README.rst
- Vagrantfile
- etc/requirements.txt
- libweasyl/requirements.txt
Upgrades the Vagrant .box file to use Debian 9.1 (and associated libraries), and Postgresql 9.6.
Wheels for Weasyl specific libraries are not available yet, so build must be performed as it exists in the Makefile (i.e., with no-binary). If this pull is approved, back end wheel builds will be upgraded as well as production workers are upgraded.
> Modify Vagrantfile to use Debian 9

- static/images/favicon.svg
- templates/common/page_start.html
This pull request should add the Safari pinned icon to Weasyl. The code added is straightforward, it adds the favicon SVG in the same folder as the PNG favicon and adds the needed meta tags to the page start.
This fulfills Issue #255.
A preview of the icon is below and on [this page](http://owo.zone/weasyl.html):
> [Enhancement] Add Safari Pinned Icon

- assets/scss/site.scss
It’s an easy improvement that makes the site usable.
> Make thumbnails visible without JavaScript

- weasyl/cron.py
Change stems from a discussion on Gitter surrounding the changes made to support plausible deniability of email addresses (20180111@0242 EST). Further, most people who sign up for a website will almost immediately turn around and confirm their account.
Two days (approximately) is more than a fair window to permit completion of a signup request.
> Purge logincreate records after two days

- libweasyl/libweasyl/alembic/versions/8cde5e07b63f_store_invalid_email_in_logincreate.py
- libweasyl/libweasyl/models/tables.py
- templates/admincontrol/acctverifylink.html
- templates/admincontrol/admincontrol.html
- templates/admincontrol/pending_accounts.html
- weasyl/controllers/admin.py
- weasyl/controllers/routes.py
- weasyl/cron.py
- weasyl/login.py
Provides a new admin-restricted page to view, and optionally purge, account creation requests in the ``logincreate`` table. In the event of an invalid ``logincreate`` record, the email wouldn't normally be displayed. So this also adds an ``invalid_email_addr`` field to the ``logincreate`` table to permit storing the originally provided email (since the email field is unique to the table).
Addresses the first and second proposals in #302.
> Add the ability for admins to view accounts pending creation

- Vagrantfile
Since merging Pillow 5.0.0, Pillow will fail to build from source during a ``vagrant provision`` with output similar to the following:
https://paste.weasyldev.com/show/As7fqhhIenbAIFLVvcy3/
https://paste.weasyldev.com/show/yxFdoHekq1T0jhHid5Qn/
Adding the packages in the diff permit a build of the package to succeed from a clean ``vagrant destroy/make distclean/vagrant up``. Packages sourced from https://pillow.readthedocs.io/en/latest/installation.html#building-on-linux
> Vagrant: Add required packages to build Pillow>=5.0.0

- etc/requirements.txt
- templates/directorcontrol/emailblacklist.html
- weasyl/controllers/director.py
- weasyl/login.py
- weasyl/test/conftest.py
- weasyl/test/login/test_create.py
Requested by Hendikins. Also, leverage [this repository's](https://github.com/ivolo/disposable-email-domains) list of disposable email domains to block known domains that could potentially be used for spam.
Tweak the director's view of adding additional domains to blacklist to be a text area, one-per-line addition, which enables adding domains much easier.
> Email Blacklist: Block subdomains of blacklisted domains

- templates/admincontrol/finduser.html
- weasyl/controllers/admin.py
- weasyl/moderation.py
Enhancements for #124.
Enables /admincontrol/finduser to search for banned and/or suspended users, and for searching for accounts created before, after, or between a range of dates. Providing a username/ID/email is optional with the new features (e.g., you can search for all banned accounts created between X-Y dates).
> /admincontrol/finduser Enhancements

- templates/common/page_end.html
- templates/common/page_start.html
- weasyl/define.py
- weasyl/middleware.py
`www.weasyl.com` doesn’t look authoritative for `cdn.weasyl.com`, but that’s only maybe the reason.
> Don’t cdnify resources to push

- weasyl/commishinfo.py
The API we were using has shut down in a way that causes Marketplace to crash. The new one requires some setup (an account contact), so turn it off as a quick fix for now.
> Disable Marketplace currency conversion temporarily

- weasyl/controllers/api.py
- weasyl/controllers/messages.py
- weasyl/message.py
Faster query; tags only when necessary (i.e. when requested via the API). Also corrects sorting order to its intended descending welcome id, previously descending submission time because both tables used `unixtime`. Only affects collection notifications, but affects them significantly.
> Improve loading times for submission notifications

- weasyl/controllers/decorators.py
- weasyl/controllers/two_factor_auth.py
- weasyl/controllers/user.py
- weasyl/login.py
- weasyl/middleware.py
- weasyl/oauth2.py
- weasyl/profile.py
- weasyl/sessions.py
- weasyl/test/conftest.py
- weasyl/test/db_utils.py
- weasyl/test/login/test_authenticate_bcrypt.py
- weasyl/test/login/test_signin.py
- weasyl/test/resetpassword/test_force.py
- weasyl/test/web/test_login.py
There are more security fixes, but they involve changing the `sessions` table so should come after the removal of guest sessions. The session token fix, on the other hand, is a dependency of that change.
> Fix session token not changing on login and potential CSRF timing vulnerability

- templates/user/profile.html
- weasyl/controllers/api.py
- weasyl/controllers/profile.py
- weasyl/followuser.py
- weasyl/frienduser.py
- weasyl/profile.py
Profile pages don’t display a random selection of those anymore. Also saves queries for their profile pictures and fixes a bug that might never have been encountered where users who accepted friend requests but never sent them, never followed anybody, and were never followed by anybody would appear not to have friends.
> Avoid redundant friend, follow, and follower queries on profile page

- weasyl/controllers/content.py
- weasyl/test/web/test_journals.py
``edit_journal_post_`` lacks the decorators to check for a login session early and check for the CSRF token. This adds them, as well as adds two tests to validate our assumption that we do, indeed, need a login and a CSRF token to edit a journal.
> Check login session early for editing journals

- libweasyl/libweasyl/alembic/versions/b194ab27295e_ensure_no_guest_sessions_remain_in_.py
- libweasyl/libweasyl/models/tables.py
- libweasyl/libweasyl/models/users.py
- weasyl/define.py
- weasyl/middleware.py
- weasyl/test/web/test_login.py
Breaks form submissions by guests (log in, register, reset password) when those forms have been left open since before 2018-06-20.
> Remove CSRF token backwards compatibility for guest sessions

- weasyl/middleware.py
- weasyl/wsgi.py
Add `?sql_debug` to a request to get timing information in response headers.
> Add query timing option for devs

- libweasyl/libweasyl/alembic/versions/36b4c0d45d93_add_index_for_profile_favorites.py
- libweasyl/libweasyl/models/tables.py
Drops the query for a profile with 27,498 favorites from 200 ms to 2 ms locally, but the difference on production should be more significant.
> Improve profile load times for users with large numbers of public favorites

- .travis-install.sh
pytest-cov 2.6.1 appears to have dropped support for pytest<3.5 (something 2.6.0 claimed to do); CI uses pytest 3.3.0 somehow (we don’t specify it, but it looks like there’s no virtualenv and the Travis build configuration in use includes it). Attempt at a minimal change to get things working again.
> Use exact versions of codecov and pytest-cov in CI

- Makefile
- libweasyl/Makefile
Some packages have begun to depend on Python 3 build tools (i.e., ``flake8``), though currently the pre-built wheels still support Python 2.
Uses pip's ``--no-binary`` option to exclude ``sanpera``, ``psycopg2cffi``, and ``lxml`` from wheels, since issues have been encountered per Charmander using the pre-built wheels.
Fixes #474.
> Prefer wheels over building from source. Fixes #474.

- libweasyl/setup.py
lxml 4.3.1 frees something it shouldn’t when you set the `tail` of top-level elements in `fragment_fromstring` with `create_parent=True`:
```python
from lxml import html
rendered = u"<p></p>\n"
fragment = html.fragment_fromstring(rendered, create_parent=True)
fragment[0].tail = u""  # use after free
```
This happens in Weasyl with *every* Markdown rendering.
> Downgrade lxml to 4.3.0 to avoid memory corruption

- templates/common/thumbnail_grid_item.html
- templates/etc/index.html
- templates/etc/popular.html
- templates/etc/search.html
- templates/message/submissions_thumbnails.html
- templates/user/characters.html
- templates/user/collections.html
- templates/user/favorites.html
- templates/user/profile.html
- templates/user/submissions.html
Next iteration for lazy loading.
Lazy loading images above the fold is considered an anti-pattern, and may result in images not beginning to load until everything else has loaded. This PR attempts to pick sane values in places where the ``thumbnail_grid_item`` items are used.
Additionally, adds the ability to exempt ``thumbnail_grid_item`` from lazy-loading by default, via ``lazy_load=False`` being passed as a parameter to the template rendering call.
> Add lazy load exemptions for above-the-fold images

- weasyl/controllers/settings.py
- weasyl/frienduser.py
`frienduser.request` still has concurrency problems, which can be addressed when `settings` ('' or 'p') turns into a single `pending` column.
> Remove unused parts of frienduser

- libweasyl/libweasyl/images.py
- libweasyl/libweasyl/models/media.py
- weasyl/define.py
- weasyl/submission.py
This might change the behaviour of libweasyl.images.
Necessary for Python 3, #629.
> Make all division Python-3-compatible

- etc/SETTINGS.txt
- libweasyl/libweasyl/images.py
- libweasyl/libweasyl/models/content.py
- libweasyl/libweasyl/models/helpers.py
- libweasyl/libweasyl/models/media.py
Popup is strange. It has existed since the beginning of accessible weasyl-old history, and was unused even then. It *was* used in weasyl3 for submission thumbnails, but it just doesn’t seem like a very good idea in general (it scales smaller images up). I still don’t know why it’s called what it is.
I’ve confirmed that there are no popups in production, so this won’t affect API consumers, either.
```
weasyl=# SELECT count(*) FROM submission_media_links WHERE link_type = 'popup';
count
-------
0
(1 row)
weasyl=# SELECT count(*) FROM media_media_links WHERE link_type = 'popup';
count
-------
0
(1 row)
weasyl=# SELECT count(*) FROM user_media_links WHERE link_type = 'popup';
count
-------
0
(1 row)
weasyl=# SELECT count(*) FROM character WHERE position('+' in settings) != 0;
count
-------
0 …
```
> Remove unused media type popup

- libweasyl/libweasyl/legacy.py
- libweasyl/libweasyl/models/users.py
- libweasyl/libweasyl/text.py
- weasyl/define.py
- weasyl/report.py
- weasyl/test/db_utils.py
libweasyl.legacy.plaintext didn’t do what it claimed to, and the Unicode-stripped password check in libweasyl.models.users was broken because of it – but it isn’t used in the current version of Weasyl anyway.
libweasyl.legacy.login_name was similar to weasyl.define.get_sysname, and intended to be used in the same situations. It’s better to have only one. It’s now reexported by weasyl.define (though unfortunately not explicitly, like via `__all__`), because it seemed like changing its references would be unnecessary noise.
> Remove broken libweasyl.legacy.plaintext and its unused dependent; merge libweasyl.legacy.login_name and weasyl.define.get_sysname

- weasyl/polecat.py
This should get the request breakdown graphs (e.g. https://status.weasyl.com/munin/weasyl.com/web2.i.weasyl.com/weasyl_request_length_weasyl_1.html) working again.
> Fix int/float mixups in stat collection

- etc/SETTINGS.txt
- libweasyl/libweasyl/alembic/versions/39f2ff4b7fa6_remove_unused_favorite_settings.py
- libweasyl/libweasyl/models/tables.py
Confirmed that there are no rows in production with a non-empty value.
> Remove unused favorite.settings

- weasyl/test/web/common.py
- weasyl/test/web/test_characters.py
- weasyl/test/web/test_submissions.py
It’s a bit fragile – reuploading *after* uploading the second submission would reuse a cached cover from that upload and therefore not cover what I’m about to refactor – but it’s something.
> Add web tests for reuploaded thumbnails and covers on visual submissions

- weasyl/spam_filtering.py
The built-in ConnectionError class is only Python 3, and requests doesn't inherit from it (rather, the base error class inherits from IOError).
Fix arising from #654, where I had my IDE set to Python 3.5, and there's a built-in in Python 3.
> Use requests.exceptions.ConnectionError as the exception class

- templates/manage/ignore.html
- weasyl/controllers/settings.py
- weasyl/ignoreuser.py
- make it not cut off at 20 users,
- sort it case-insensitively,
- show when it’s empty,
- and clean up its code.
> Fix up list of ignored users

- config/site.config.txt.example
- weasyl/emailer.py
- weasyl/login.py
- weasyl/profile.py
- weasyl/resetpassword.py
- weasyl/test/conftest.py
Allows not having a local MTA or similar, convenient for containers. Should work without configuration changes in production, since the VMs have SMTP on localhost.
Fixes #700.
> Switch to smtplib to send mail

- weasyl/controllers/detail.py
- weasyl/controllers/profile.py
- weasyl/submission.py
- weasyl/templates/detail/submission.html
- weasyl/templates/user/profile.html
- weasyl/test/conftest.py
- weasyl/test/test_submission.py
- In-folder navigation on submissions
- Featured/latest submissions on profile pages
- Twitter cards/OGP metadata
This is a performance improvement, since it avoids a redirect that’s already done the full work of `submission.select_view`.
> Update link format for some of the most common sources of old-style submission links

- libweasyl/Makefile
Attempting to install libweasyl would fail otherwise. Gitter reference/discussion: https://gitter.im/Weasyl/weasyl?at=5e3ce917433e1d40399e8220
(I got tired of manually adding the constraint file to each branch checkout. So let's fix it once and for all.)
> Reference constraint file for weasyl to fix libweasyl builds.

- weasyl/polecat.py
Twisted doesn’t use `getClientIP` internally anymore (it’s deprecated), so this override does nothing. For Weasyl’s side, we use Pyramid’s `client_addr`, which always reads `X-Forwarded-For`.
> Remove custom Twisted Request implementation

- weasyl/define.py
- weasyl/profile.py
used on the viewer whenever thumbnails are displayed, for example.
Also fixes a bug: the guest `userid` is `0`, not `None`.
> Eliminate another round trip for profile.jsonb_settings

- weasyl/cron.py
- weasyl/define.py
- weasyl/templates/common/page_end.html
It’s adding a Memcached round trip for something that’s not even functional right now. (When/if we bring it back, it should probably only count registered users.)
> Remove active users

- weasyl/controllers/profile.py
- weasyl/folder.py
Instead of showing a random submission from a random selection of three non-empty folders, show the most recently updated folders with the corresponding most recent updates.
Fixes #725, and behaviour when all submissions in a folder are friends-only.
The query is slower, but hopefully not slow enough to cause problems in practice.
> Make profile folder previews show most recent, obey blacklists

- Dockerfile
- libweasyl/libweasyl/alembic/versions/5a6d74c75fa6_fill_in_favorite_count_for_submissions.py
- libweasyl/libweasyl/models/tables.py
- libweasyl/libweasyl/test/common.py
- weasyl/favorite.py
- weasyl/profile.py
- weasyl/submission.py
and apply code simplifications accordingly.
You know, I’m still not sure whether this is guaranteed to produce consistent results with concurrent queries, but it’s easy to detect and correct after the migration has run if not.
> Fill in submission.favorites for submissions that haven’t been favorited since its introduction

- libweasyl/libweasyl/alembic/versions/652d9ba475f0_remove_thumbnail_legacy_links.py
- weasyl/api.py
- weasyl/media.py
They existed for the temporary thumbnail migration tool, which has been removed.
> Remove thumbnail-legacy links

- libweasyl/libweasyl/alembic/versions/e0320dc462db_convert_frienduser_timestamps_to_.py
- libweasyl/libweasyl/models/tables.py
Converts frienduser and watchuser tables to use DateTime(timezone=True) instead of WeasylTimeColumn. 
Helps out with #68
> Convert frienduser and watchuser table timestamps

- assets/js/scripts.js
- weasyl/controllers/content.py
- weasyl/middleware.py
- weasyl/templates/common/page_end.html
so it doesn’t block scripts.js despite being unusable on most pages and unused on the rest when the user doesn’t type anything.
This can be further improved by splitting out defang (and splitting up scripts.js in general).
> Load marked.js lazily

- libweasyl/libweasyl/images_new.py
ImageMagick identifies them as JPEGs, so the error message is confusing. Just produce a thumbnail from the first image in the sequence, like the old thumbnailing would have.
Tested with real MPOs, but I can’t find any existing small or redistributable MPOs, or a convenient way to create them.
Fixes WEASYL-160.
> Don’t fail Pillow thumbnailing for MPOs

- assets/js/zxcvbn-check.js
- libweasyl/libweasyl/alembic/versions/c5074772185a_improve_password_reset.py
- libweasyl/libweasyl/models/tables.py
- weasyl/controllers/user.py
- weasyl/cron.py
- weasyl/resetpassword.py
- weasyl/templates/email/reset_password.html
- weasyl/templates/etc/forgotpassword.html
- weasyl/templates/etc/resetpassword.html
- weasyl/test/db_utils.py
- weasyl/test/resetpassword/conftest.py
- weasyl/test/resetpassword/test_prepare.py
- weasyl/test/resetpassword/test_request.py
- weasyl/test/resetpassword/test_reset.py
Fixes #698.
- always send an e-mail so people aren’t left guessing as to whether something is eventually coming (and so various behaviours are independent of whether an account with the given e-mail address exists on the site)
- look up e-mail case-insensitively (but prefer case-sensitive for backwards compatibility – there are 700+ e-mail addresses with multiple associated accounts because registration is case-sensitive! registration being `<input type="email">` but password reset being `<input type="text">` might have made this even more visible than usual on mobile.)
- look up e-mail at reset time so that a password reset request sent to an account’s previous address doesn’t work (even though the window was only one hour)
- drop 5-minute timer that starts on visiting the link, because …
> Improve password reset

- libweasyl/libweasyl/alembic/versions/77c5bbd1fa3d_remove_unused_stored_comment_indent.py
- libweasyl/libweasyl/models/tables.py
- weasyl/comment.py
- weasyl/controllers/content.py
- weasyl/shout.py
- weasyl/test/test_comment.py
Right now, hidden top-level shouts always show up as having been hidden by nobody, and any other level is (almost always) “[hidden by moderator]”. This happens because the indent level is being used as the `hidden_by` user id.
This set of changes fixes that, and also removes stored `indent`s altogether, since the field has been calculated entirely by `weasyl.comment.thread()` for some time now. The migration should be applied after switching over the workers.
> Fix shout deletion being misattributed, and clean up related code

- weasyl/controllers/admin.py
- weasyl/moderation.py
- weasyl/templates/admincontrol/finduser.html
Single rebased commit from #744.
> remove dependency on storify from controllers/admin.py

- weasyl/controllers/profile.py
- weasyl/journal.py
- weasyl/templates/user/journals.html
using the same style as the site update list. It’s a bit strange to put an avatar beside each one without a feature of adding different avatars to different journals, but it doesn’t look right to have nothing there either.
| before | after |
|---|---|
| ![Screenshot_2020-05-07 Argsei's journals — Weasyl](https://user-images.githubusercontent.com/1889843/81242981-0b2a2d00-8ffe-11ea-9f6a-a8d4ddb0ac86.png) | ![Screenshot_2020-05-07 Argsei's journals — Weasyl](https://user-images.githubusercontent.com/1889843/81242992-12513b00-8ffe-11ea-8661-43a1243f1876.png) |
> Add excerpts and dates to journal list

- Vagrantfile
- containers/nginx.conf
Required by #822 (which raised visual submission limit to 50MiB)
> Update nginx client_max_body_size to 55m

- weasyl/resetpassword.py
- weasyl/test/resetpassword/test_request.py
The input was normalized with `emailer.normalize_address()`, but not lowercased.
> Fix password reset requests with uppercase in local part

- weasyl/controllers/content.py
Removes the default value of ``boop`` from ``coverfile`` in the ``submit_literary_post_`` route.
While this doesn't _break_ anything exactly, if, for example, someone with an intercepting proxy (or just deleting the element from the developer tools ... for whatever reason) decides to just not send the blank ``coverfile`` form parameter, the text "boop" would propagate down to Sanpera to try and be decoded. That is, the blank/empty ``coverfile`` normally received nullifies the default string received into the parameter as set in the function definition, and this only appears in non-standard conditions.
(When the ``<input>`` for ``coverfile`` is deleted)
```
2020-06-24T02:42:14+0000 [stderr#error] Traceback (most recent call last):
2020-06-24T02:42:14+0000 [stderr#error]   File …
```
> Set coverfile default value to empty string

- weasyl/controllers/detail.py
> remove dependency on storify from controllers/detail.py

- assets/js/scripts.js
Known vulnerability I discounted when Markdown previews were introduced, completely wrongly because:
- self-XSS is a serious issue
- moderators can edit others’ submission descriptions, with the same instantly-rendering Markdown preview as everywhere else
An upcoming improved fix for this will be eliminating Markdown completely (with any backwards compatibility not including a client-side preview).
Fixes #888.
> In Markdown preview, avoid running inline event handlers and loading resources before HTML sanitization

- weasyl/errorcode.py
- weasyl/submission.py
- weasyl/test/web/common.py
- weasyl/test/web/test_submissions.py
- Not filtering out targets on the Weasyl network is a recipe for disaster (even if nothing *should* privilege HTTP requests based on their source)
- The requests aren’t made through a proxy as is the case with outgoing mail, so this stops Weasyl servers’ private IP addresses (behind Cloudflare) from being revealed to just anyone.
List of sources in conveniently verifiable form at <https://github.com/Weasyl/waxpost-chrome/blob/cfe0ce252b60e4f0a2a3def94bec08f4c96abd5c/manifest.json#L14-L22>.
> Restrict crossposting to source domains supported by Waxpost

- README-docker.md
Build of test container fails without ``--build-arg`` included; launch of ``weasyl-test`` container fails without ``.pytest_cache`` directory existing.
> Fix README-docker.md to permit execution of tests

- libweasyl/libweasyl/test/test_text.py
- libweasyl/libweasyl/text.py
- Adds more tests, bringing up measured line/branch coverage on libweasyl.text to 100% (the “uncovered” `continue` and the associated partial coverage on the `elif` seems to be some kind of coverage bug)
- Simplifies and fixes `<img>` removal
I recommend looking at the diff with whitespace changes ignored.
> Markdown cleanup

- libweasyl/libweasyl/defang.py
- libweasyl/libweasyl/test/test_text.py
- libweasyl/libweasyl/text.py
- weasyl/test/web/test_api.py
I benchmarked a typical small comment, and this was about twice as fast. The difference is probably more with Markdown that’s longer, more complicated, or both. But also:
- the user-link-finding improvement fixes a bug that removed newlines unintentionally
- the etree cleanup makes the code cleaner
> Speed up Markdown rendering

- weasyl/submission.py
Unused since the beginning of accessible history, 2012-11-19.
> Remove unused `submission.select_*` parameter `exclude`

- etc/SETTINGS.txt
- libweasyl/libweasyl/models/tables.py
- weasyl/errorcode.py
- weasyl/submission.py
Encores, pools, collaborations, locking. All verified to not be present in the production database, and I didn’t find them anywhere else in the code, although they’re hard to look for because settings columns are terrible.
> Remove unused and mostly unimplemented content-item settings

- etc/SETTINGS.txt
- libweasyl/libweasyl/alembic/versions/981bd4df447e_remove_obsolete_tag_blocking_type_.py
- libweasyl/libweasyl/models/tables.py
- weasyl/profile.py
- weasyl/test/test_search.py
`l` indicated use of a tag blocklist, which is the only kind now. ~64k profiles have this applied.
```
=> SELECT round(max(userid), -4) AS max FROM profile;
┌────────┐
│  max   │
├────────┤
│ 190000 │
└────────┘
=> SELECT round(max(userid), -4) AS max FROM profile WHERE config ~ 'l';
┌───────┐
│  max  │
├───────┤
│ 80000 │
└───────┘
```
> Remove obsolete profile config for tag blocking type

- weasyl/middleware.py
- weasyl/polecat.py
because since Twisted 16.3.0, requests never spend time queued. See the relevant deprecation notices at https://twistedmatrix.com/documents/21.2.0/api/twisted.web.http.Request.html (“in 16.3 this method was changed to become a no-op, as Request objects are now never queued”) and https://twistedmatrix.com/trac/ticket/8320.
This should be followed up with the removal of `(queued: $sent_http_x_queued_time_spent)` from the Nginx timing log configuration.
> Remove measurement of time a request spends queued

- README-docker.md
- config/site.config.txt.example
- containers/run
- containers/run-nginx
Looking back to #885, a few lingering issues that are resolved (and eliminates the troubleshooting section entirely, and avoids re-symlinking ``sh`` to ``bash`` (which may or may not cause further issues, since Ubuntu might not expect it)):
- Adds ``storage/static`` as a created directory. (The nginx step would otherwise complain about this not existing.)
- Uncomments lines in ``site.config.txt.example``, permitting the template file to be used as-is without manually uncommenting the lines.
- Since Ubuntu is symlinking `/bin/sh` to `dash`, when on Ubuntu as a host invocations of the Docker scripts fails (`containers/run: 3: UID: parameter not set`). Converts usages of `$UID` to `$(id -u)`.
This was created by running through `README-docker.md` top-to-bottom, to ensure everything works as …
> Docker fixes

- weasyl/cache.py
- weasyl/middleware.py
Python 3!
In addition to being monotonic, operations on its return values are more precise, because zero is closer in time – but that effect is a decimal place or two past what we even display.
> Time request handling parts with monotonic `clock.perf_counter`

- weasyl/submission.py
I thought there was something to clear the link before it was switched to Pillow? That might have been `image_representations`.
> Fix visual submission reuploads not regenerating WebP thumbnail

- libweasyl/libweasyl/alembic/versions/259bc2d8e46c_remove_inter_media_links.py
- libweasyl/libweasyl/models/content.py
- libweasyl/libweasyl/models/media.py
- libweasyl/libweasyl/models/tables.py
- libweasyl/libweasyl/models/test/test_media.py
- libweasyl/libweasyl/test/common.py
- weasyl-apidocs/source/index.rst
- weasyl/api.py
- weasyl/character.py
- weasyl/orm.py
- weasyl/templates/detail/character.html
- weasyl/test/web/test_api.py
They add a lot of complexity along with other types of overhead, and are generated lazily in confusing ways while providing only a small benefit (not regenerating covers when identical submission files are reuploaded).
This slightly breaks the public HTTP API’s backwards-compatibility, but anything making use of the removed properties is already broken.
Can be deployed safely without running the migration, making it reversible (except for the missing links on new media).
> Remove inter-media links

- assets/scss/site.scss
- ci/site.config.txt
- config/site.config.txt.example
- weasyl/controllers/content.py
- weasyl/controllers/user.py
- weasyl/define.py
- weasyl/emailer.py
- weasyl/templates/etc/signup.html
- weasyl/weasyl.tac
- weasyl/wsgi.py
We’re already going through Cloudflare and can use its captcha challenge on the `/signup` path.
Removing this means a better signup experience, less code complexity, slightly less exposure to third parties for Weasyl users, and a slightly nicer Content-Security-Policy when that’s implemented.
> Remove Google CAPTCHA

- libweasyl/libweasyl/cache.py
- weasyl/controllers/api.py
- weasyl/controllers/profile.py
- weasyl/define.py
- weasyl/login.py
- weasyl/profile.py
- weasyl/searchtag.py
- weasyl/test/web/conftest.py
- weasyl/test/web/test_journals.py
It’s a disaster waiting to happen, since it maps distinct inputs to identical outputs. Luckily, the only arbitrary Unicode text passed to a cache function before this was tags, which discard information in a compatible way.
Preprocess before cache lookups to avoid creating keys incompatible with Memcached and also improve hit rate.
Also remove the unused configurable Memcached prefix.
> Remove Dogpile cache key mangler

- libweasyl/libweasyl/text.py
- weasyl/config.py
- weasyl/test/login/test_authenticate_bcrypt.py
- weasyl/test/test_submission.py
Now they pass in green instead of yellow, and without a bunch of noise!
> Fix test deprecation warnings

- docker-compose.yml
Actions which require external access (e.g., embedding a YouTube link via multimedia submissions) will fail unless web can access external network resources. This fixes it by adding an external network to the ``web`` container.
Found as a result of testing #1056, which without this fix would result in an HTTP504 (because it couldn't actually get out _to_ the external resource).
> Add external-web network to web container

- etc/requirements.txt
- libweasyl/libweasyl/cache.py
- libweasyl/libweasyl/conftest.py
- libweasyl/setup.py
- weasyl/test/conftest.py
- weasyl/weasyl.tac
I don’t think the gzip can be triggered by anything realistic – maybe 1MB of blocked tags. (But we should increase the object size limit anyway if that happens.)
I also tried packing the constant `ct` and `v` metadata separately, as well as msgpack, but they varied from slightly slower to much slower.
Development deployment:
- `./wzl restart memcached`
Production deployment:
> Perform JSON serialization at the pylibmc client level; remove gzip

- assets/js/scripts.js
- weasyl/comment.py
- weasyl/controllers/content.py
- weasyl/templates/common/comment_thread.html
- Label comment deletion action with “Delete” instead of “Hide”
- Allow deletion of comment with replies that are all deleted
- Fix new shout replies showing up as “undefined”
> Assorted comment improvements

- weasyl/commishinfo.py
Unnoticed until now because it’s disabled in both production and dev, but I tested it as part of the sentry-sdk migration. :)
> Fix exchange rate fetching for Python 3

- libweasyl/libweasyl/alembic/versions/ed80016034fd_index_sorted_inbox_view.py
- libweasyl/libweasyl/models/tables.py
`ORDER BY noteid` in `weasyl.note.select_inbox`/`select_outbox` without an index that includes `noteid` means PostgreSQL decides not to use the `userid`/`otherid` indexes, resulting in query times >1s to view some small inboxes.
Index `(otherid, noteid)` so `WHERE otherid = $1 ORDER BY noteid [DESC]` can use it; same for `userid`.
> Index sorted inbox/outbox views

- assets/js/scripts.js
- assets/scss/site.scss
- weasyl/controllers/routes.py
- weasyl/controllers/user.py
- weasyl/define.py
- weasyl/templates/common/page_start.html
- weasyl/templates/etc/login_box.html
- weasyl/templates/etc/signin.html
- weasyl/test/web/test_login.py
- weasyl/test/web/test_site_updates.py
- Fixes search query (for example) disappearing when toggling SFW mode
- Fixes #697
- Removes potential point of poorly-handled failure: login modal XHR (also saving the corresponding delay)
- Makes logout a POST, and idempotent
- Removes unused frontend things
Known issue: the 2FA form’s redirect can still be specified with a URL parameter, and it still strips the querystring. Will be fixed in the upcoming 2FA refactor.
> Login experience improvements

- .github/workflows/tests.yml
- Dockerfile
- assets/js/scripts.js
- ci/site.config.txt
- config/site.config.txt.example
- etc/requirements.txt
- libweasyl/libweasyl/models/tables.py
- libweasyl/libweasyl/models/users.py
- weasyl/controllers/decorators.py
- weasyl/controllers/settings.py
- weasyl/controllers/two_factor_auth.py
- weasyl/controllers/user.py
- weasyl/define.py
- weasyl/login.py
- weasyl/middleware.py
- weasyl/profile.py
- weasyl/sessions.py
- weasyl/templates/common/page_start.html
- weasyl/test/conftest.py
- weasyl/test/login/test_signin.py
- weasyl/test/web/test_api.py
- weasyl/test/web/test_blacklist.py
- weasyl/test/web/test_characters.py
- weasyl/test/web/test_journals.py
- weasyl/test/web/test_login.py
- weasyl/test/web/test_notes.py
- weasyl/test/web/test_site_updates.py
- weasyl/test/web/test_submissions.py
- weasyl/wsgi.py
It’s supported by all modern browsers. Allows guests to be cookie-free and to share cache.
Some of the 2FA edge cases are probably broken (and it looks like they already were before), but I’d like to refactor that soon anyway.
SQLAlchemy is horrible as usual.
Intentionally missing a migration to delete `csrf_token` for now, just in case we want to undo this.
> Rely on `Origin` header for CSRF prevention

- libweasyl/libweasyl/alembic/versions/bcb0d75b6f8b_remove_outdated_index_condition.py
- libweasyl/libweasyl/models/tables.py
- weasyl/submission.py
`favorites` has a `NOT NULL` constraint now.
Migration should run before app deployment.
> Remove outdated index condition

- libweasyl/libweasyl/alembic/versions/af3b8d60b7ba_add_submission_tag_history_index.py
- libweasyl/libweasyl/models/tables.py
Oops.
Makes the submission tag history page not scan every row.
> Add submission tag history index

- libweasyl/libweasyl/text.py
Possibly introduced by a new libxml2 version?
Bug found by @kfkitsune.
> Fix rendered Markdown trailing `<` caused by new `lxml.html.tostring` trailing newline

- weasyl/errorcode.py
Most people who run into this do so because their browser doesn’t support the `Origin` header, not because they’re the victim of a CSRF attempt.
Fixes #1113.
> Give more likely advice in CSRF check failure message

- assets/opensearch.xml
- build.js
- containers/nginx/nginx.conf
- weasyl/templates/common/page_start.html
Allows Weasyl search to be added to browsers.
- The icon is assets/img/favicon.svg. Its size as declared in opensearch.xml is 32x32 because current Firefox seems to render it at the declared size, *then* scale, even though it’s an SVG.
- The resource doesn’t have a hash suffix because it needs to self-update.
> Add OpenSearch description

- README.md
- wzl
Docker changed to have docker compose as a plugin, and the command docker-compose no longer is default; a backwards-compatible check was created to allow older versions to still execute the script correctly (for the moment, at least).
Raised as an issue at: https://github.com/Weasyl/weasyl/pull/1372#issuecomment-1627634230
> bug: wzl: correct invocation of docker compose

- .github/workflows/codeql-analysis.yml
Newer defaults and not permissions I intentionally removed, I think?
> Bring CodeQL GitHub Actions workflow more in line with defaults

- assets/scss/components/_date-picker.scss
- assets/scss/help.scss
- assets/scss/mod.scss
- assets/scss/signup.scss
- assets/scss/site.scss
- build.js
- weasyl/controllers/info.py
- weasyl/controllers/moderation.py
- weasyl/controllers/settings.py
- weasyl/controllers/user.py
- weasyl/templates/admincontrol/admincontrol.html
- weasyl/templates/common/page_start.html
- weasyl/templates/modcontrol/modcontrol.html
- weasyl/templates/modcontrol/reports.html
Makes the global stylesheet slightly lighter and the source slightly easier to navigate.
Does not move `components/option` to `mod`, because it should be used in more places.
> Separate out (more) CSS specific to signup, help, and moderation pages

- assets/scss/site.scss
Dates back to before the first open-source commit. Possibly related to group pages?
> cleanup: Remove some unused `#user-nav.group` CSS

- assets/scss/components/_user-tabs.scss
- assets/scss/site.scss
- weasyl/character.py
- weasyl/collection.py
- weasyl/controllers/profile.py
- weasyl/define.py
- weasyl/journal.py
- weasyl/moderation.py
- weasyl/submission.py
- weasyl/templates/common/user_tabs.html
- weasyl/templates/user/characters.html
- weasyl/templates/user/collections.html
- weasyl/templates/user/favorites.html
- weasyl/templates/user/followed.html
- weasyl/templates/user/following.html
- weasyl/templates/user/friends.html
- weasyl/templates/user/journals.html
- weasyl/templates/user/profile.html
- weasyl/templates/user/shouts.html
- weasyl/templates/user/submissions.html
The counts respect the viewer’s rating preference. Sets up for some future changes:
* determining whether SFW mode has an effect when the configured rating preference is the same between SFW mode and non, so we can avoid confusingly showing a toggle that does nothing
* making blocked tag filtering a visible operation on pages of results (which itself sets up for better pagination and performance improvements through caching and lightened database load)
I’d like to provide counts for favorites and individual folders too, but they’re more involved. Ideally, counts would be stored in the database and updated eagerly; PostgreSQL makes it hard.
> Add post counts to user tabs

- assets/scss/mod.scss
- weasyl/controllers/moderation.py
- weasyl/moderation.py
- weasyl/templates/modcontrol/suspenduser.html
- Use native date picker for release date
- Replace use of server-time-zone-dependent `weasyl.define.convert_unixdate` with consistent UTC 00:00
Separated from #1397.
> Improve suspension date handling

- weasyl/controllers/settings.py
Disabled form fields aren’t submitted.
> Fix site preferences to be submittable when rating preference is disabled

- libweasyl/html.py
- libweasyl/test/test_html.py
- libweasyl/test/test_text.py
- libweasyl/text.py
- weasyl/controllers/detail.py
- weasyl/controllers/profile.py
`markdown_excerpt` is more complete (renders Markdown, normalizes whitespace), correct (produces plain text), and robust (uses `lxml.html`, which doesn’t crash on the same malformed input that `html.parser` does).
> Replace `strip_html` with `markdown_excerpt`

- .github/workflows/tests.yml
Codecov wants us to use their v4 action and corresponding new uploader, which is terribly designed and doesn’t work at all on Alpine anymore; it now rate limits tokenless uploads to the point that Codecov effectively hasn’t worked for the last month.
Let’s see if providing the token to the v3 action (despite it only being documented to be required for private repos for that version of the action) helps.
> Upload coverage to Codecov with API token

- assets/js/scripts.js
Fixes #1106 by ensuring newly-created comment reply boxes do not contain what the user typed into the root comment box. This prevents `addMarkdownPreview` from trying to update the Markdown preview of a reply box that has not actually had its Markdown preview initialized.
> Don't copy root comment box's text to reply (#1106)

- libweasyl/alembic/versions/63baa2713e72_remove_signup_birthdate_column.py
- libweasyl/models/tables.py
- weasyl/controllers/user.py
- weasyl/login.py
- weasyl/test/login/test_create.py
- weasyl/test/login/test_get_account_verification_token.py
- weasyl/test/login/test_verify.py
The removal has been deployed for a while now, so nobody should be inconvenienced by breaking postback of the old version of the form.
Migration runs after deployment.
> Clean up leftover signup birthdate logic and database column

- weasyl/define.py
- weasyl/metrics.py
- weasyl/middleware.py
Uncached notification count queries can be triggered unpredictably by almost every page and take a highly variable amount of time depending on the user (up to 7 seconds). Keeping this separate should make individual route metrics more useful.
> Separate metrics for retrieving notification counts from overall request metrics

- config/site.config.txt.example
- gunicorn.conf.py
- weasyl/controllers/user.py
- weasyl/define.py
- weasyl/errorcode.py
- weasyl/templates/common/turnstile.html
- weasyl/templates/etc/forgotpassword.html
- weasyl/templates/etc/signup.html
- weasyl/test/conftest.py
- weasyl/turnstile.py
There’s a lot of rate limiting missing from Weasyl, but anonymous endpoints that send mail are a good start. This also prepares for further signup streamlining.
The server-side validation intentionally uses `requests.post` instead of `weasyl.define.http_post` (which is also unused anywhere else), because the `"httpError"` error message is worse than the generic unexpected server-side failure, and exposing the message of an arbitrary `Exception` seems like a really bad idea besides.
> Add Cloudflare Turnstile challenge to signup and password reset

- .github/workflows/tests.yml
- Dockerfile
- ci/site.config.txt
- config/site.config.txt.example
- docker-compose.yml
- libweasyl/alembic/alembic.ini.example
- libweasyl/conftest.py
- poetry.lock
- pyproject.toml
- weasyl/test/test_define.py
Serious flaw of unknown concrete impact on the app.
Markdown rendering has a similar bug (`libweasyl.text.markdown("foo\x00bar") == "<p>foo</p>\n"`), but I don’t think there’s anywhere on the site it can be used to harmful effect if it can even be triggered at all.
Also, psycopg2cffi is unmaintained now with noisy deprecation warnings, and it didn’t fix the issue that was the main motivation for originally trying it.
Production configuration needs to be changed before deployment (both `site.config.txt` and `alembic.ini`), and development configuration needs to be updated with `wzl configure`.
This security fix is already deployed.
> Prevent truncation at NUL in SQL query parameters by replacing psycopg2cffi with psycopg2

- weasyl/controllers/settings.py
- weasyl/oauth2.py
> [!NOTE]
> As a security fix, this is already deployed.
A relatively minor security fix, for form submissions on malicious URLs. Examples:
- `/control/editfolder/…?settings=f&settings=m&settings=u&settings=n` – add unwanted folder options if owner of folder submits this form
- `/control/apikeys?add-api-key=y&add-key-description=%3E:)` – add an unintended (but still random and inaccessible) API key with an attacker-controlled description
- revoke OAuth consumers
- add unintended pending collections to accept or reject operations
The problematic pattern is a form with an empty `action`, preserving the querystring on form submission, combined with the form’s endpoint failing to distinguish between data from the request body and querystring.
The tag filters endpoint wasn’t actually …
> Avoid reading form data from query string that produced the form

- weasyl/test/web/test_interaction.py
Split from the now-closed #1454.
> Add test for note permissions

- libweasyl/defang.py
- libweasyl/test/test_text.py
> [!NOTE]
> As a security fix, this is already deployed.
Speaking of CVE-2023-24329…
Yes! Weasyl has one of the most obvious XSSes, in 2024.
I’m looking forward to getting to the point of implementing a real Content-Security-Policy, a real safe document model that isn’t created from arbitrary HTML, ….
> Fix `<a href=" javascript:">` with leading space bypassing HTML filter

- weasyl/controllers/settings.py
- weasyl/controllers/user.py
- weasyl/define.py
- weasyl/forms.py
- weasyl/test/web/test_redirect.py
> [!NOTE]
> As a security fix, this is already deployed.
> Redirect hardening

- weasyl/templates/user/profile.html
- weasyl/test/web/test_profile.py
Per discussion in the developer chatroom.
Includes a new, parametrized test for making sure `rel="me"` appears if and only if the given contact info creates a URL link.
> Add rel="me" to profile links

- weasyl/controllers/settings.py
The button was removed in dbc14312819f7f58c9abe1cd5c3570338678ace9.
> Remove handling for removed “add more” social links button

- weasyl/controllers/interaction.py
- weasyl/controllers/user.py
- weasyl/define.py
- weasyl/profile.py
> [!NOTE]
> As a security fix, this is already deployed.
Sending requests that cause lookup of a user-provided user id (the endpoints changed in this commit) with soon-to-exist user ids could break things, which was exploitable to cause availability issues.
> Avoid caching negative results for lookups of username by user id

- docker-compose.yml
This must be a recent change to Docker Compose (since this happens on a clean `./wzl up -d`, which has been documented in the README as the preferred way to get started for a while), but I haven’t found a corresponding entry in the release notes with a quick look.
To be honest, I don’t know exactly what name it tries to pull in this situation (`_/weasyl`?), and whether there’s a corresponding security issue. I’ve registered the “weasyl” name on Docker Hub in case that ever closes a hole.
I really dislike Docker.
> Ensure shared Docker Compose images are never pulled, even when running without anything built

- weasyl/searchtag.py
Affects suggested tag actions only.
> fix: Make `searchtag.get_or_create` return id instead of list

- weasyl/test/web/test_submissions.py
While `api-unstable` implies the API could change at any time, I have already broken this feature once (in #1467, fixed by charmander in #1486), and I would like to help prevent future regressions of this feature. This test can always be deleted if it would get in the way of major API interface changes.
> Add test for rejecting and undoing a suggested tag

- assets/scss/fonts/_museo500.scss
- assets/scss/site.scss
- build.js
- containers/nginx/nginx.conf
- weasyl/middleware.py
- weasyl/templates/common/page_start.html
It’s very small, so the extra preload entry and request are a lot of overhead. This also allows it to be minified, compressed, and versioned together with the rest of the CSS.
I’ve also removed the TTF `src` entry, since our entire browser support range now supports WOFF, and unquoted the `format` keywords (since the spec says that’s preferred, [Firefox should support it as of version 105][1], and it’s a little bit cleaner and shorter).
[1]: https://bugzilla.mozilla.org/show_bug.cgi?id=650372
> Include `@font-face` declaration in main CSS file

- assets/scss/site.scss
The removed section is a duplicate of the following section, minus one additional rule at the end:
https://github.com/Weasyl/weasyl/blob/6fd9b5969b67188e75baa09eeee0255bd36373b2/assets/scss/site.scss#L639-L669
> Remove duplicate dl.leaders rules in site.scss

- assets/scss/fonts/_museo500.scss
The license Fontspring associates with the web font version of Museo doesn’t mention this, but it doesn’t hurt.
> Credit Museo font’s designer in minified CSS

- weasyl/macro.py
Move Patreon back into the correct spot for the list to be in alphabetical order, then add:
* Archive of Our Own
* Ko-fi
* Picarto
* Piczel
* Telegram
* Twitch
I figured this can be proposed ahead of time while I work on the rest of the contact link redesign.
> Add more contact sites

- assets/js/scripts.js
- weasyl/templates/common/user_tools.html
- Add confirmations for the following actions:
- unfollowing a user
- unfavoriting a submission
- ignoring a user
- Replace one-off confirmation logic for unfriending a user with `data-confirm`
- Replace `XMLHttpRequest` with `fetch` in client-side submission favoriting logic
I was not able to cleanly use `data-confirm` for unfavoriting a submission, since the next `submit` event handler, which does the web request to favorite or unfavorite the submission, will then immediately fire regardless of the user's choice for the confirmation dialog. Perhaps the `e.preventDefault();` in the `data-confirm` handler could be changed to ignore all following event handlers instead of just the default event handler, but I didn't pursue this since I don't know if this would break another part of Weasyl. …
> Confirm more 'destructive' actions

- weasyl/middleware.py
- weasyl/oauth2.py
Endpoints under `/api/oauth2` already disabled for a while at the Cloudflare level, but I’m not completely sure that there’s no way to slip a request past that somehow. Hotfix in depth for a global impersonation vulnerability.
(This is the change that I’ve been merging main into before each deployment since finding the OAuth vulnerability. It’s time to stop doing that.)
> Completely disable OAuth

- weasyl/templates/control/2fa/disable.html
- weasyl/templates/control/2fa/generate_recovery_codes.html
- weasyl/templates/control/2fa/init_qrcode.html
- weasyl/templates/control/2fa/init_verify.html
- weasyl/templates/etc/forgotpassword.html
- weasyl/templates/etc/login_box.html
- weasyl/templates/etc/resetpassword.html
- weasyl/templates/etc/signin_2fa_auth.html
namely in the login box and password reset/2FA flows.
> Add/update `autocomplete`, `inputmode`, and `required` where appropriate

- weasyl/controllers/interaction.py
- weasyl/controllers/marketplace.py
- weasyl/controllers/messages.py
- weasyl/controllers/profile.py
> Add titles to titleless pages

- README.md
Documenting the answers to two common questions in the developer chatroom.
> Document `./wzl build build-assets` and `PermissionError` fix in readme

- weasyl/searchtag.py
The order needs to match the input in order for Dogpile to create the right cache entry associations.
This probably caused the tag id confusion bug, though it’s hard to reproduce or test because it depends on PostgreSQL’s query plan. Anyway, it was definitely wrong.
> fix: Ensure `searchtag._get_or_create` returns results in correct order

- wzl
It seems to require a service with `profiles` to have one of its profiles selected explicitly to build it with `docker compose build`, even though https://docs.docker.com/reference/compose-file/profiles/ says that
> A service is ignored by Compose when none of the listed profiles match the active ones, **unless the service is explicitly targeted by a command**.
I suspect this is a bug in Docker Compose, but the new code is cleaner anyway.
> dev: Make wzl compatible with new Docker Compose 2.36.0

- containers/nginx/nginx.conf
See `libweasyl.models.media.MediaItem.display_url`.
This is a symlink in production.
> dev: Fix media with SHA-256 starting with `ad`

- .github/workflows/tests.yml
- Dockerfile
pip is resolving a Poetry dependency to a version that isn’t the one we have pinned. Luckily, `--require-hashes` still catches it.
Both `-c requirements.txt` and `--no-deps` can work around the issue.
This was fixed at some point between pip 23.0.1 and the current pip 25.1.1, but I don’t want to add an additional Poetry-style lockfile for a pip upgrade and further bloat the image besides.
We should be able to upgrade to a fresher base image soon enough anyway.
> Work around pip 23.0.1 dependency resolution bug

- libweasyl/alembic/versions/bb2c42b6df18_remove_max_sfw_rating.py
- weasyl/profile.py
The change has been deployed for a while and we’re probably not going to roll it back, so it’s fine to leave any unlikely recovery needs to database backups.
The migration can run before or after web server deployment.
> cleanup: Remove leftovers of configurable SFW mode rating limit

- assets/scss/site.scss
- config/weasyl-staff.example.py
- libweasyl/staff.py
- libweasyl/test/data/weasyl-staff.yaml
- weasyl/controllers/admin.py
- weasyl/controllers/info.py
- weasyl/define.py
- weasyl/staff_config.py
- weasyl/test/searchtag/test_associate.py
- weasyl/test/searchtag/test_edit_global_tag_restrictions.py
- weasyl/test/searchtag/test_get_tag_restrictions.py
- weasyl/test/test_staff_config.py
- weasyl/test/web/test_site_updates.py
Closes #1519
`technical_staff` is still allowed in the configuration file to prevent an outage when upgrading past this commit.
> Remove Techs role

- weasyl/controllers/api.py
- weasyl/controllers/decorators.py
- weasyl/controllers/routes.py
- weasyl/controllers/user.py
- weasyl/oauth2.py
Making a critical security decorator that’s easy to overlook a little more robust.
> Require every non-`GET` route to define an explicit CSRF check policy

- weasyl/controllers/general.py
- weasyl/controllers/search.py
- weasyl/search.py
- weasyl/templates/common/page_start.html
- weasyl/test/test_search.py
- adds the title ‘Posts tagged “foo”’ (or “Journals”, “Characters”) to single-tag searches
- adds canonical URLs to searches
- speeds up single-tag searches when not logged in (down to <10 ms from as high as >1 s)
> Speed up single-tag guest searches; improve search page metadata

- assets/js/view-count.js
- build.ts
- weasyl/character.py
- weasyl/controllers/content.py
- weasyl/controllers/detail.py
- weasyl/controllers/profile.py
- weasyl/controllers/routes.py
- weasyl/define.py
- weasyl/journal.py
- weasyl/profile.py
- weasyl/submission.py
- weasyl/templates/common/page_start.html
- weasyl/templates/detail/character.html
- weasyl/templates/detail/journal.html
- weasyl/templates/detail/submission.html
- weasyl/templates/user/profile.html
- weasyl/test/test_define.py
- weasyl/test/test_submission.py
- weasyl/test/web/test_api.py
- reduces “views” counted from crawlers and link metadata retrieval
- eliminates the only write (except for session updates) on initial post/profile load
- enables future caching
- includes related fixes and cleanup
> Asynchronous view counting

- assets/js/scripts.js
- build.ts
- weasyl/templates/common/page_end.html
instead of getting it from an attribute in the page, to harden against a hypothetical `<div id="scripts" data-marked="evil">` injection and improve the effectiveness of a future Content-Security-Policy.
> Make lazily-loaded marked script’s `src` a constant
